print (("Nguyễn Chí Bảo").center(78,'-'))
a = input("Nhập chuỗi 1: \n")
b = input("Nhập Chuỗi 2: \n")
c = input("Nhập chuỗi 3: \n") 
d = int(input ("Nhập index: \n"))
print ("Chiều dài chuỗi s1 = ",len(a))
print ("Chiều dài chuỗi s2 = ",len(b))
print ("Chiều dài chuỗi s3 = ",len(c))
print ("Chuỗi 4 = ",a[d:])
print ("Chuỗi s2 lặp lại 2 lần = ",b*2)